linters:
    enable-all: true
    disable:
        - maligned

        # TODO: fix these
        - gosimple
        - staticcheck
        - ineffassign
        - structcheck
        - lll
        - gochecknoglobals
        - nakedret
        - gosec
        - unparam
        - interfacer
        - unused
        - golint

linters-settings:
    golint:
        min-confidence: 0.1

issues:
    exclude:
        - Using the variable on range scope `tt` in function literal
        - Using the variable on range scope `tc` in function literal
