builds:
    -
        main: ./cmd/pke
        binary: pke
        env:
            - CGO_ENABLED=0
        ldflags: "-s -w -X main.Version={{ .Version }} -X main.CommitHash={{ .ShortCommit }} -X main.BuildDate={{ .Date }}"
        goos:
            - linux
        goarch:
            - amd64

archive:
    name_template: "pke_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
    name_template: "pke_checksums.txt"

changelog:
    skip: true
