builds:
    -
        main: ./cmd/pke
        binary: pke
        env:
            - CGO_ENABLED=0
        ldflags: "-s -w -X main.Version={{ .Version }} -X main.CommitHash={{ .ShortCommit }} -X main.BuildDate={{ .Date }}"
        goos:
            - linux
        goarch:
            - amd64

archive:
    name_template: "pke-{{ .Version }}"
    format: binary

checksum:
    name_template: "pke-{{ .Version }}-checksums.txt"

changelog:
    skip: true

s3:
    -
       bucket: banzaicloud.com
       region: eu-central-1
       folder: "downloads/pke"
